// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {git} from '../models';
import {main} from '../models';

export function GetCurrentBranch(arg1:string):Promise<string>;

export function GetDiff(arg1:string,arg2:git.ChangedFile):Promise<string>;

export function GetStatus(arg1:string):Promise<Array<git.ChangedFile>>;

export function OpenRepository(arg1:string):Promise<main.RepoSummary>;

export function SelectDirectory():Promise<string>;
